name: Code Hygiene

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install nox
          pip install poetry
          pip install nox-poetry
      - name: Run Linting
        run: |
          echo "# Linting Issues" > linting_report.md
          echo "| Path | Row | Col | Code | Msg |" >> linting_report.md
          echo "| --- | --- | --- | --- |  --- |" >> linting_report.md
          nox --sessions lint >> linting_report.md
          sed -i -e 's/$/    /' linting_report.md
      - name: Save Linting Report
        if: ${{ failure() }}
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: linting_report.md

  static-type-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install nox
          pip install poetry
          pip install nox-poetry
      - name: Run Type Checking
        run: nox --sessions mypy
      - name: Save MyPy Report
        if: ${{ failure() }}
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: mypy_report.txt/index.txt

  Tests_and_Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install nox
          pip install poetry
          pip install nox-poetry
      - name: Generate Coverage Report
        run: nox --sessions tests coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  Safety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install nox
          pip install poetry
          pip install nox-poetry
      - name: Run Safety
        run: nox --sessions safety
